### ISSUE TITLE
calico-upgrade complains of "unclean" data after data was cleaned

### ISSUE THREAD

**Issue by bcreane** [projectcalico/calico-upgrade#11]
After manually cleaning calico data from etcdv3 datastore, calico-upgrade still complains that the datastore is not clean.

Steps to reproduce are here:
https://github.com/projectcalico/calico/pull/1523

Afterwards, run

calico-upgrade -l debug dry-run --output-dir=~ --apiconfigv3 etcdv3.yaml --apiconfigv1 etcdv1.yaml

**Comment by bcreane** [comment]
[error.txt](https://github.com/projectcalico/calico-upgrade/files/1570310/error.txt)

**Comment by bcreane** [comment]
Note this issue was opened by @emanic.

**Comment by song-jiang** [comment]
I am not be able to reproduce this issue with latest calico-upgrade binary.

**Comment by gunjan5** [comment]
This is working as expected. The issue was when we clear the etcd after we apply the manifest. So if you follow these steps:

1. start 2.6.4 cluster
2. calico-upgrade dry-run
3. calico-upgrade start
4. apply the v3 manifests
5. (optional) calico-upgrade complete
6. try to delete the v3 data
7. calico-upgrade dry-run

You will see these errors, because once the v3 manifests are applied, Calico v3 components such as kube-controller, CNI etc will start writing data to the v3 datastore frequently, even after you delete all the data.

Wiping out the data will only work after calico-upgrade start and before applying the v3 manifests.

**Comment by yingxin-gh** [comment]
@gunjan5  How to delete the v3 data ? Any document ?
